//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Area_Producto
    {
        public int Numero_Documento { get; set; }
        public int Id_Area { get; set; }
        public int Codigo { get; set; }
        public int Cantidad { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual Area_Operativa_Produccion Area_Operativa_Produccion { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
