//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.Area_Producto = new HashSet<Area_Producto>();
        }
    
        public int Codigo { get; set; }
        public string Nombre { get; set; }
        public decimal Costo { get; set; }
        public string Descripcion { get; set; }
        public string Unidad_Medida { get; set; }
        public string Tipo_Producto { get; set; }
        public int Stock { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Id_Almacen { get; set; }
    
        public virtual Almacen Almacen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Area_Producto> Area_Producto { get; set; }
    }
}
