//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trabajador
    {
        public int Id_Trabajador { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public int DNI { get; set; }
        public string Telefono { get; set; }
        public string Correo { get; set; }
        public string Cargo { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Id_Almacen { get; set; }
    
        public virtual Almacen Almacen { get; set; }
    }
}
